"use client";

import Link from "next/link";
import { useSession } from "next-auth/react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { motion } from "framer-motion";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative border-b-2 border-black overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 md:py-32">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center"
          >
            <h1 className="text-5xl md:text-7xl font-bold mb-6 tracking-tight">
              COGNISCOPE
            </h1>
            <p className="text-xl md:text-2xl mb-4 max-w-3xl mx-auto">
              AI-Powered Cognitive Assessment
            </p>
            <p className="text-lg md:text-xl text-gray-700 mb-8 max-w-2xl mx-auto">
              Early detection and prevention of cognitive decline through
              advanced AI analysis
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              {session ? (
                <Link href="/dashboard">
                  <Button size="lg" variant="primary">
                    Go to Dashboard
                  </Button>
                </Link>
              ) : (
                <>
                  <Link href="/auth/signup">
                    <Button size="lg" variant="primary">
                      Get Started
                    </Button>
                  </Link>
                  <Link href="/auth/login">
                    <Button size="lg" variant="secondary">
                      Sign In
                    </Button>
                  </Link>
                </>
              )}
            </div>
          </motion.div>
        </div>

        {/* Animated Background Elements */}
        <div className="absolute top-0 left-0 w-full h-full pointer-events-none overflow-hidden -z-10">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
            className="absolute top-10 right-10 w-32 h-32 border-4 border-red-600 opacity-10"
          />
          <motion.div
            animate={{ rotate: -360 }}
            transition={{ duration: 25, repeat: Infinity, ease: "linear" }}
            className="absolute bottom-10 left-10 w-48 h-48 border-4 border-black opacity-5"
          />
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 border-b-2 border-black">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              How It Works
            </h2>
            <p className="text-lg text-gray-700 max-w-2xl mx-auto">
              Three simple steps to understand your cognitive health
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
              viewport={{ once: true }}
            >
              <Card variant="bordered" className="h-full">
                <div className="flex items-center justify-center w-16 h-16 bg-black text-white text-2xl font-bold mb-4">
                  1
                </div>
                <h3 className="text-2xl font-bold mb-3">Create Account</h3>
                <p className="text-gray-700">
                  Sign up in seconds and access your personalized cognitive
                  assessment dashboard.
                </p>
              </Card>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              viewport={{ once: true }}
            >
              <Card variant="bordered" className="h-full">
                <div className="flex items-center justify-center w-16 h-16 bg-red-600 text-white text-2xl font-bold mb-4">
                  2
                </div>
                <h3 className="text-2xl font-bold mb-3">Take AI Test</h3>
                <p className="text-gray-700">
                  Complete a scientifically-validated cognitive assessment
                  generated by advanced AI.
                </p>
              </Card>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              viewport={{ once: true }}
            >
              <Card variant="bordered" className="h-full">
                <div className="flex items-center justify-center w-16 h-16 bg-black text-white text-2xl font-bold mb-4">
                  3
                </div>
                <h3 className="text-2xl font-bold mb-3">Get Report</h3>
                <p className="text-gray-700">
                  Receive detailed insights, risk assessment, and personalized
                  recommendations.
                </p>
              </Card>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Why CogniScope?
            </h2>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {[
              {
                title: "AI-Powered Analysis",
                description:
                  "Advanced Gemini AI evaluates your cognitive performance with medical-grade accuracy.",
              },
              {
                title: "Early Detection",
                description:
                  "Identify potential cognitive decline indicators before clinical symptoms appear.",
              },
              {
                title: "Personalized Reports",
                description:
                  "Get tailored recommendations and preventive strategies based on your results.",
              },
              {
                title: "Track Progress",
                description:
                  "Monitor your cognitive health over time with comprehensive reporting.",
              },
            ].map((benefit, index) => (
              <motion.div
                key={benefit.title}
                initial={{ opacity: 0, x: index % 2 === 0 ? -20 : 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
              >
                <Card variant="elevated" className="h-full">
                  <h3 className="text-xl font-bold mb-2">{benefit.title}</h3>
                  <p className="text-gray-700">{benefit.description}</p>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-black text-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Take Control of Your Cognitive Health
            </h2>
            <p className="text-lg mb-8 text-gray-300">
              Start your assessment today and gain valuable insights into your
              brain health.
            </p>
            {!session && (
              <Link href="/auth/signup">
                <Button size="lg" variant="danger">
                  Start Free Assessment
                </Button>
              </Link>
            )}
          </motion.div>
        </div>
      </section>
    </div>
  );
}
